name: Deploy Frontend
on:
  push:
    branches:
      - main
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t yuktiarora22/react-test -f ././client/Dockerfile.dev ././client
      - run: docker run -e CI=true yuktiarora22/react-test npm run test

      - name: Build and tag images
        run: |
          docker build -t yuktiarora22/multi-client ././client
          docker build -t yuktiarora22/multi-nginx ././nginx
          docker build -t yuktiarora22/multi-server ././server
          docker build -t yuktiarora22/multi-worker ././worker
     
      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'
     
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v21
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: 'frontend'
      #     environment_name: 'Frontend-env'
      #     existing_bucket_name: 'elasticbeanstalk-ap-south-1-529088284858'
      #     region: 'ap-south-1'
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip